config/routes.rb
Rails.application.routes.draw do
  get 'project/showlist/', to: "project#showlist"
  get '/project/deal_with', to: "project#deal_with" ,as: 'deal_with'

  resources :list_container
  resources :project
  root to: "project#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container.rb
class Container < ApplicationRecord
  has_many :item
      
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :container
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/list_container_controller.rb
class ListContainerController < ApplicationController
  def index

    @list_container = Container.all
    
  end

  def create
    if session['container'] != nil && session[:item] != nil
      @container = Container.new(container_type: session['container'])
      @container.save
      @items = session[:item]
      @items.each do |item|
        @packing_style = item['packing_style'] 
        @length =  item['length'].to_i
        @heigth =  item['heigth'].to_i
        @width =  item['width'].to_i
        @weigth =   item['weigth'].to_i
        @cog_heigth_type =  item['cog_heigth_type']
        @cog_heigth =  item['cog_heigth'].to_i
        
        @item_into_container = @container.item.new(
                container_id: @container.id,
                packing_style: @packing_style ,
                length:  @length,
                heigth:  @heigth,
                width:   @width,
                weigth:  @weigth,
                cog_heigth_type:  @cog_heigth_type,
                cog_heigth:  @cog_heigth
              )
        @item_into_container.save
      end
      session.delete(:item)
      session.delete('container')
    end
    redirect_to list_container_index_path

  end

  def show
    @item = Item.where(container_id:  params[:id])
  end

  def destroy
    @item = Item.where(container_id:  params[:id])
    @container = Container.find(params[:id])

    @item.each do |item|
      item.destroy
    end
    @container.destroy
    redirect_to list_container_index_path

  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController

  before_action :initialize_session
  def index 
    @session_item_count = session[:item].count
    if session['container'] == nil
        session['container'] = params[:container_type]
    end
    

    if params[:item] != nil
      session[:item] << params[:item]
    end
    
    @session_item = session[:item]
    @session_container = session['container']

  end

  def showlist
    @Total_error = params[:error]
    @session_item = session[:item]
    @session_container = session['container']
  end

  def deal_with
    @Total_error = ContainerCheck.call(session['container'],session[:item])
    # session.delete(:item)
    #   session.delete('container')
    redirect_to project_showlist_path(:error => @Total_error)
  end

  def initialize_session
    session[:item] ||= []
    session['container'] 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_container_helper.rb
module ListContainerHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_container/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Project | SCS</title>
</head>

<body>

    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="index.html"><%= image_tag  "f8001e55b20d74d39e53558cdb8b159f.jpg", height:100 %> </a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li>Home</li>
                        <li>About us</li>
                        <li>New & Event's</li>
                        <li>Solution</li>
                        <li>O3</li>
                        <li>Contact</li>
                    </ul>

                </nav>
                

            </div>
        </div>
    </div>

    <!-- ------------ Project -------------- -->
    
    <div class="payment">
        <div class="row">
           <div class="col-1"> 
                <h3>List Container</h3>
                <table>
                    <thead>
                        <tr>
                        <th>Container Type</th>
                        <th>Time</th>
                        <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @list_container.each do |container| %>
                        <tr>
                            <td><%= container.container_type %></td>
                            <td><%= container.created_at %></td>
                            <td><%= link_to 'Show', list_container_path(id: container.id)  %></td>
                            <td><%= link_to 'Destroy',list_container_path(id: container.id),method: :delete %></td> 
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                        <a><%= link_to "Back" , root_path%></a>
            </div>    
        </div>
    </div>     

    <!-- ------------footer----------- -->

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>71 Ayer Rajah Crescent, Singapore </h3>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15664.031587358322!2d106.73526995!3d11.038034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1a4fd6a29643%3A0x9fcb7b4d484cb3b7!2s71%20Ayer%20Rajah%20Crescent%2C%2001%2003%2C%20Singapore%20139951!5e0!3m2!1svi!2s!4v1640786095700!5m2!1svi!2s" width="250" height="75" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
        

                <div class="footer-col-4">
                    <h3>Resources</h3>
                    <ul>
                        <li><a>• Career </a>   </li>
                        <li><a>• FAQs </a></a></li> 
                        <li><a>• Company policie</a></li>
                        <li><a>• Info Center</a></li>
                    </ul>
                </div>

                <div class="footer-col-4">
                    <h3>Contact</h3>
                    <ul>
                        <li><a>• Hotline: (+65) 6352 1371 </a>  </li>
                        <li><a>• info@scs71.com</a></li>
                        
                    </ul>
                </div>

            </div>
        </div>
    </div>


   
    
</body>

</html>

app/views/list_container/show.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Project | SCS</title>
</head>

<body>

    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="index.html"><%= image_tag  "f8001e55b20d74d39e53558cdb8b159f.jpg", height:100 %> </a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li>Home</li>
                        <li>About us</li>
                        <li>New & Event's</li>
                        <li>Solution</li>
                        <li>O3</li>
                        <li>Contact</li>
                    </ul>

                </nav>
                

            </div>
        </div>
    </div>

    <!-- ------------ Project -------------- -->
    
    <div class="payment">
        <div class="row">
           <div class="col-1"> 
                <h3>Item Container</h3>
                <table>
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Packing style</th>
                            <th>Lenght </th>
                            <th>Height</th>
                            <th>Width</th>
                            <th>Weight</th>
                            <th>Cog Height type</th>
                            <th>Cog Height</th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @item.each_with_index do |item,index| %>
                        <tr>
                            <th><%= index+1 %></th>
                            <td><%= item.packing_style %></td>
                            <td><%= item.length %></td>
                            <td><%= item.heigth %></td>
                            <td><%= item.width %></td>
                            <td><%= item.weigth %></td>
                            <td><%= item.cog_heigth_type %></td>
                            <td><%= item.cog_heigth %></td>
                            
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                        <a><%= link_to "Back" , list_container_index_path%></a>
            </div>    
        </div>
    </div>     

    <!-- ------------footer----------- -->

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>71 Ayer Rajah Crescent, Singapore </h3>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15664.031587358322!2d106.73526995!3d11.038034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1a4fd6a29643%3A0x9fcb7b4d484cb3b7!2s71%20Ayer%20Rajah%20Crescent%2C%2001%2003%2C%20Singapore%20139951!5e0!3m2!1svi!2s!4v1640786095700!5m2!1svi!2s" width="250" height="75" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
        

                <div class="footer-col-4">
                    <h3>Resources</h3>
                    <ul>
                        <li><a>• Career </a>   </li>
                        <li><a>• FAQs </a></a></li> 
                        <li><a>• Company policie</a></li>
                        <li><a>• Info Center</a></li>
                    </ul>
                </div>

                <div class="footer-col-4">
                    <h3>Contact</h3>
                    <ul>
                        <li><a>• Hotline: (+65) 6352 1371 </a>  </li>
                        <li><a>• info@scs71.com</a></li>
                        
                    </ul>
                </div>

            </div>
        </div>
    </div>


   
    
</body>

</html>

app/views/project/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>item | SCS</title>
</head>

<body>

    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="index.html"><%= image_tag  "f8001e55b20d74d39e53558cdb8b159f.jpg", height:100 %> </a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li>Home</li>
                        <li>About us</li>s
                        <li>New & Event's</li>
                        <li>Solution</li>
                        <li>O3</li>
                        <li>Contact</li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

    <!-- ------------ project -------------- -->
    
    <div class="project">
        <div class="row">

           <div class="col-1"> 
                <div id="cart" >
                    <form action= "/project">
                    <table style="width:120%; "  > 
                        <tr>
                            <th colspan="6" >Container type</th> 
                            <th>

                                <% if @session_container == nil %>
                                    <select name="container_type" id="container_type"> 
                                        <option value="FR20">FR20</option> 
                                        <option value="FR40">FR40</option> 
                                        <option value="OT20">OT20</option> 
                                        <option value="OT40">OT40</option> 
                                    </select>
                                <% else %>
                                    <p> <%= @session_container %> </p>  
                                <% end %>
                                
                            </th>
                        </tr>
                        <tr>
                            <th>Packing style</th>
                            <th>Length </th>
                            <th>Heigth</th>
                            <th>Width</th>
                            <th>Weigth</th>
                            <th>Cog Height type</th>
                            <th>Cog Height</th>
                        </tr>
                        <tr>
                            <td>
                                <select name="item[packing_style]" id="packing_style">
                                    <option value="BARE">Bare</option>
                                    <option value="SKID">SKID</option>
                                    <option value="CASE">CASE</option>
                                    <option value="CRATE">CRATE</option>
                                </select>
                            </td>
                            <td><input value="0" name="item[length]" size="1" style="border-bottom: 0px solid #00BCD4; margin-top: 0px;margin-bottom: 0px;"/></td>
                            <td><input value="0" name="item[heigth]" size="1" style="border-bottom: 0px solid #00BCD4; margin-top: 0px;margin-bottom: 0px;"/></td>
                            <td><input value="0" name="item[width]"  size="1" style="border-bottom: 0px solid #00BCD4; margin-top: 0px;margin-bottom: 0px;"/></td>
                            <td><input value="0" name="item[weigth]" size="1" style="border-bottom: 0px solid #00BCD4; margin-top: 0px;margin-bottom: 0px;"/></td>
                            <td>
                                <select name="item[cog_heigth_type]" id="cog_type">
                                    <option value="MANUAL">MANUAL</option>
                                    <option value="TBA">TBA</option>
                                    <option value="HALF HEIGHT">HALF HEIGHT</option>
                                </select>
                            </td>
                            <td><input value="0" name="item[cog_heigth]" size="1" style="border-bottom: 0px solid #00BCD4; margin-top: 0px;margin-bottom: 0px;/>"></td>

                        </tr>
                        
                    </table>
                    <input style="margin-left: 570px;" id="submit" type="Submit" name="Submit" value="Add item"  onclick="Purchase()" > 
                    </form>
                                  
                </div>
            </div>  

     <div class="col-1"> 
                <div id="list_item" >
                    <h3 style= "text-align: center;" >List item</h3>
                    <table style="width:120%; "  > 
                        <tr>
                            <th colspan="8" >Container type</th> 
                            <th colspan="4" >
                                <p> <%= @session_container %> </p> 
                            </th>
                        </tr>
                        <tr>
                            <th>STT</th>
                            <th>Packing style</th>
                            <th>Length </th>
                            <th>Heigth</th>
                            <th>Width</th>
                            <th>Weigth</th>
                            <th>Cog Heigth type</th>
                            <th>Cog Heigth</th>
                        </tr>

                        <% if @session_item != nil %>
                            <% @session_item.each_with_index  do |item,index| %>
                                <th><%= index+1 %></th> 
                                <% item.each do |key,value| %>
                                    <% if key == "cog_heigth" %>
                                        <th><%= value %></th> 
                                        <tr></tr>
                                    <% else %>
                                        <th><%= value %></th>
                                    <% end %>
                                <% end %>
                            <% end %>
                            
                        <% end %>

                    </table>
                    <ul>
                        <li><%= link_to "Submit" , deal_with_path() ,methob: :get %></li>
                        <li><%= link_to "Container list" , list_container_index_path  %></li>
                    </ul>
                    
                </div>
                                
            </div>  
        </div>

    </div>     

    <!-- ------------footer----------- -->

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>71 Ayer Rajah Crescent, Singapore </h3>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15664.031587358322!2d106.73526995!3d11.038034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1a4fd6a29643%3A0x9fcb7b4d484cb3b7!2s71%20Ayer%20Rajah%20Crescent%2C%2001%2003%2C%20Singapore%20139951!5e0!3m2!1svi!2s!4v1640786095700!5m2!1svi!2s" width="250" height="75" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
        

                <div class="footer-col-2">
                    <h3>Resources</h3>
                    <ul>
                        <li><a>• Career </a>   </li>
                        <li><a>• FAQs </a></a></li> 
                        <li><a>• Company policie</a></li>
                        <li><a>• Info Center</a></li>
                    </ul>
                </div>

                <div class="footer-col-2">
                    <h3>Contact</h3>
                    <ul>
                        <li><a>• Hotline: (+65) 6352 1371 </a>  </li>
                        <li><a>• info@scs71.com</a></li>
                        
                    </ul>
                </div>

            </div>
        </div>
    </div>


    <script>
        function Purchase(){
            
            alert("Thank you for purchasing!");

        }

       
    </script>

    <script>
      
      $("#item").on("submit", function(e) {
        if (!this.checkValidity()) return;

        // prevent default event like submit, ...
        e.preventDefault();

        // get form input
        input = $(this).serializeArray()

        // add item to container
        $("#list_item table tr:last").after(`
          <tr>
             <td>${input[0].value}</td>
             <td>
               ${input[1].value}
             </td>
             <td>
               <button type="button" onclick="onDelete(this)">Delete</button>
               <input type="hidden" value="${input[0].value}" name="${input[0].name}">
               <input type="hidden" value="${input[1].value}" name="${input[1].name}">
               <input type="hidden" value="${input[2].value}" name="${input[2].name}">
               <input type="hidden" value="${input[3].value}" name="${input[3].name}">
               <input type="hidden" value="${input[4].value}" name="${input[4].name}">
               <input type="hidden" value="${input[5].value}" name="${input[5].name}">
               <input type="hidden" value="${input[6].value}" name="${input[6].name}">
               <input type="hidden" value="${input[7].value}" name="${input[7].name}">
               <input type="hidden" value="${input[8].value}" name="${input[8].name}">
             </td>
          </tr>
         `)

        //reset form after submit
        $(this).get(0).reset()
      })

      /*********
      * Handle remove item from container
      */
      function onDelete(button) {
        $(button).closest("tr").remove()
      }

    </script>
    
</body>

</html>

app/views/project/showlist.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Project | SCS</title>
</head>

<body>

    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="index.html"><%= image_tag  "f8001e55b20d74d39e53558cdb8b159f.jpg", height:100 %> </a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li>Home</li>
                        <li>About us</li>
                        <li>New & Event's</li>
                        <li>Solution</li>
                        <li>O3</li>
                        <li>Contact</li>
                    </ul>

                </nav>
                

            </div>
        </div>
    </div>

    <!-- ------------ Project -------------- -->
    
    <div class="payment">
        <div class="row">

           <div class="col-1"> 
                <div id="cart" >
                    <table style="width:120%; "  > 
                        <tr>
                            <th colspan = "7">Container type</th> 
                            <th>FR20</th>                            
                        </tr>
                        <tr>
                            <th colspan = "8">Item</th> 
                        </tr>
                        <tr>
                            <th>STT</th>
                            <th>Packing style</th>
                            <th>Lenght </th>
                            <th>Height</th>
                            <th>Width</th>
                            <th>Weight</th>
                            <th>Cog Height type</th>
                            <th>Cog Height</th>
                        </tr>
                        
                    </table>
                </div>

                
            </div>    
        </div>

    </div>     

    <!-- ------------footer----------- -->

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>71 Ayer Rajah Crescent, Singapore </h3>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15664.031587358322!2d106.73526995!3d11.038034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1a4fd6a29643%3A0x9fcb7b4d484cb3b7!2s71%20Ayer%20Rajah%20Crescent%2C%2001%2003%2C%20Singapore%20139951!5e0!3m2!1svi!2s!4v1640786095700!5m2!1svi!2s" width="250" height="75" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
        

                <div class="footer-col-4">
                    <h3>Resources</h3>
                    <ul>
                        <li><a>• Career </a>   </li>
                        <li><a>• FAQs </a></a></li> 
                        <li><a>• Company policie</a></li>
                        <li><a>• Info Center</a></li>
                    </ul>
                </div>

                <div class="footer-col-4">
                    <h3>Contact</h3>
                    <ul>
                        <li><a>• Hotline: (+65) 6352 1371 </a>  </li>
                        <li><a>• info@scs71.com</a></li>
                        
                    </ul>
                </div>

            </div>
        </div>
    </div>


    <script>
        function Purchase(){
            
            alert("Thank you for purchasing!");

        }

       
    </script>
    
</body>

</html>